# docker-compose.override.yml

# Para desenvolvimento local.
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    
    environment:
      - NODE_ENV=development

    develop:
      watch:
        - action: sync
          path: ./server 
          ignore:
            - node_modules/

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173" 
    environment:
      - NODE_ENV=development
    develop:
      watch:
        - action: sync
          path: ./web
          target: /app
          ignore:
            - node_modules/